#!/bin/sh
# entrypoint.sh — generate config/config.toml from environment variables at boot.
#
# Two supported browser modes:
#   1) REMOTE (default when BROWSERLESS_TOKEN is set)
#      → browser runs on browserless.io; backend stays under 512 MB RAM.
#   2) LOCAL (fallback, requires Chromium inside the image — heavy)
#      → only used when BROWSERLESS_TOKEN is empty AND ENABLE_LOCAL_BROWSER=1.
#
# See README.RENDER.md for details.

set -e

CONFIG_PATH="/app/config/config.toml"
# Default to a currently-free OpenRouter model. As of 2026-07 the following are
# reliably free-tier available:
#   - openai/gpt-oss-20b:free            (default, cheapest to run, small)
#   - meta-llama/llama-3.3-70b-instruct:free  (better quality, sometimes rate-limited)
#   - qwen/qwen3-next-80b-a3b-instruct:free   (strong general model)
#   - qwen/qwen3-coder:free              (best for code tasks)
#   - nousresearch/hermes-3-llama-3.1-405b:free (largest, sometimes rate-limited)
# Override by setting OPENMANUS_MODEL in the Render Environment tab.
MODEL="${OPENMANUS_MODEL:-openai/gpt-oss-20b:free}"
BASE_URL="${OPENMANUS_BASE_URL:-https://openrouter.ai/api/v1}"
API_KEY="${OPENROUTER_API_KEY:-${OPENAI_API_KEY:-YOUR_API_KEY}}"

# ---- browser config ------------------------------------------------------- #
BROWSER_SECTION=""
if [ -n "${BROWSERLESS_TOKEN:-}" ]; then
    # Remote Chromium over CDP via browserless.io
    BROWSERLESS_HOST="${BROWSERLESS_HOST:-production-sfo.browserless.io}"
    BROWSER_SECTION=$(cat <<BROWSER
[browser]
headless = true
disable_security = true
wss_url = "wss://${BROWSERLESS_HOST}/?token=${BROWSERLESS_TOKEN}&stealth=true"
BROWSER
)
    echo "[entrypoint] browser mode = REMOTE (browserless.io / ${BROWSERLESS_HOST})"
else
    BROWSER_SECTION=$(cat <<'BROWSER'
[browser]
headless = true
disable_security = true
BROWSER
)
    echo "[entrypoint] browser mode = LOCAL (requires Chromium in image)"
fi

# ---- search engine config ------------------------------------------------- #
SEARCH_SECTION=""
if [ -n "${SERPER_API_KEY:-}" ]; then
    # We route DuckDuckGo/Google traffic through Serper via an env var read by
    # a monkey-patch in serper_search.py. Set the engine to "DuckDuckGo" as the
    # primary (public HTML endpoint that doesn't require an API key), and keep
    # Baidu/Bing as fallbacks — they're all rate-limited but redundant.
    SEARCH_SECTION=$(cat <<'SEARCH'
[search]
engine = "DuckDuckGo"
fallback_engines = ["Baidu", "Bing"]
retry_delay = 30
max_retries = 2
lang = "en"
country = "us"
SEARCH
)
    echo "[entrypoint] search engine = DuckDuckGo (Serper fallback available)"
else
    SEARCH_SECTION=$(cat <<'SEARCH'
[search]
engine = "DuckDuckGo"
fallback_engines = ["Baidu", "Bing"]
retry_delay = 30
max_retries = 2
lang = "en"
country = "us"
SEARCH
)
    echo "[entrypoint] search engine = DuckDuckGo (no Serper key)"
fi

# ---- write final config -------------------------------------------------- #
mkdir -p /app/config
cat > "${CONFIG_PATH}" <<EOF
# Auto-generated by entrypoint.sh — do NOT edit inside the container.
[llm]
model = "${MODEL}"
base_url = "${BASE_URL}"
api_key = "${API_KEY}"
max_tokens = 8192
temperature = 0.0

[llm.vision]
model = "${MODEL}"
base_url = "${BASE_URL}"
api_key = "${API_KEY}"
max_tokens = 8192
temperature = 0.0

${BROWSER_SECTION}

${SEARCH_SECTION}

[mcp]
server_reference = "app.mcp.server"

[runflow]
use_data_analysis_agent = false

# Placeholder — required by app/config.py DaytonaSettings even when Daytona
# sandbox is not used. The value is never contacted unless the daytona
# sandbox tool is explicitly invoked.
[daytona]
daytona_api_key = "not-used"
EOF

echo "[entrypoint] wrote ${CONFIG_PATH} (model=${MODEL})"
exec "$@"
