#!/bin/sh
# entrypoint.sh — generate config/config.toml from environment variables
# so users don't have to commit secrets.
set -e

CONFIG_PATH="/app/config/config.toml"
MODEL="${OPENMANUS_MODEL:-deepseek/deepseek-chat-v3.1:free}"
BASE_URL="${OPENMANUS_BASE_URL:-https://openrouter.ai/api/v1}"
API_KEY="${OPENROUTER_API_KEY:-${OPENAI_API_KEY:-YOUR_API_KEY}}"

mkdir -p /app/config
cat > "${CONFIG_PATH}" <<EOF
# Auto-generated by entrypoint.sh — do NOT edit inside container
[llm]
model = "${MODEL}"
base_url = "${BASE_URL}"
api_key = "${API_KEY}"
max_tokens = 8192
temperature = 0.0

[llm.vision]
model = "${MODEL}"
base_url = "${BASE_URL}"
api_key = "${API_KEY}"
max_tokens = 8192
temperature = 0.0

[browser]
headless = true
disable_security = true

[mcp]
server_reference = "app.mcp.server"

[runflow]
use_data_analysis_agent = false
EOF

echo "[entrypoint] Wrote ${CONFIG_PATH} (model=${MODEL})"
exec "$@"
