#!/bin/sh
# entrypoint.sh — generate config/config.toml from environment variables at boot.
#
# Two supported browser modes:
#   1) REMOTE (default when BROWSERLESS_TOKEN is set)
#      → browser runs on browserless.io; backend stays under 512 MB RAM.
#   2) LOCAL (fallback, requires Chromium inside the image — heavy)
#      → only used when BROWSERLESS_TOKEN is empty AND ENABLE_LOCAL_BROWSER=1.
#
# This version also mirrors the main LLM settings into VISION_* so image
# analysis works out of the box with the same provider unless explicitly
# overridden.

set -e

CONFIG_PATH="/app/config/config.toml"

# Default to a free OpenAI-compatible provider with multimodal support.
MODEL="${OPENMANUS_MODEL:-auto:free}"
BASE_URL="${OPENMANUS_BASE_URL:-https://bazaarlink.ai/api/v1}"
API_KEY="${OPENAI_API_KEY:-${OPENROUTER_API_KEY:-YOUR_API_KEY}}"

# Vision defaults: explicit VISION_* wins; otherwise inherit main LLM config.
VISION_MODEL="${VISION_MODEL:-${OPENMANUS_MODEL:-$MODEL}}"
VISION_BASE_URL="${VISION_BASE_URL:-${OPENMANUS_BASE_URL:-$BASE_URL}}"
VISION_API_KEY="${VISION_API_KEY:-${OPENAI_API_KEY:-${OPENROUTER_API_KEY:-$API_KEY}}}"
export VISION_MODEL VISION_BASE_URL VISION_API_KEY

# ---- browser config ------------------------------------------------------- #
BROWSER_SECTION=""
if [ -n "${BROWSERLESS_TOKEN:-}" ]; then
    # Remote Chromium over CDP via browserless.io
    BROWSERLESS_HOST="${BROWSERLESS_HOST:-production-sfo.browserless.io}"
    BROWSER_SECTION=$(cat <<BROWSER
[browser]
headless = true
disable_security = true
wss_url = "wss://${BROWSERLESS_HOST}/?token=${BROWSERLESS_TOKEN}&stealth=true"
BROWSER
)
    echo "[entrypoint] browser mode = REMOTE (browserless.io / ${BROWSERLESS_HOST})"
else
    BROWSER_SECTION=$(cat <<'BROWSER'
[browser]
headless = true
disable_security = true
BROWSER
)
    echo "[entrypoint] browser mode = LOCAL (requires Chromium in image)"
fi

# ---- search engine config ------------------------------------------------- #
SEARCH_SECTION=""
if [ -n "${SERPER_API_KEY:-}" ]; then
    SEARCH_SECTION=$(cat <<'SEARCH'
[search]
engine = "DuckDuckGo"
fallback_engines = ["Baidu", "Bing"]
retry_delay = 30
max_retries = 2
lang = "en"
country = "us"
SEARCH
)
    echo "[entrypoint] search engine = DuckDuckGo (Serper fallback available)"
else
    SEARCH_SECTION=$(cat <<'SEARCH'
[search]
engine = "DuckDuckGo"
fallback_engines = ["Baidu", "Bing"]
retry_delay = 30
max_retries = 2
lang = "en"
country = "us"
SEARCH
)
    echo "[entrypoint] search engine = DuckDuckGo (no Serper key)"
fi

# ---- write final config -------------------------------------------------- #
mkdir -p /app/config
cat > "${CONFIG_PATH}" <<EOF
# Auto-generated by entrypoint.sh — do NOT edit inside the container.
[llm]
model = "${MODEL}"
base_url = "${BASE_URL}"
api_key = "${API_KEY}"
max_tokens = 8192
temperature = 0.0

[llm.vision]
model = "${VISION_MODEL}"
base_url = "${VISION_BASE_URL}"
api_key = "${VISION_API_KEY}"
max_tokens = 8192
temperature = 0.0

${BROWSER_SECTION}

${SEARCH_SECTION}

[mcp]
server_reference = "app.mcp.server"

[runflow]
use_data_analysis_agent = false

# Placeholder — required by app/config.py DaytonaSettings even when Daytona
# sandbox is not used. The value is never contacted unless the daytona
# sandbox tool is explicitly invoked.
[daytona]
daytona_api_key = "not-used"
EOF

echo "[entrypoint] wrote ${CONFIG_PATH} (model=${MODEL}, vision_model=${VISION_MODEL})"
exec "$@"
